% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  11pt,
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage{setspace}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother


% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}



\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{pdflscape}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Efficiency and acceleration in the accumulation of children's early vocabulary},
  pdfauthor={Michael C. Frank},
  pdfkeywords={Early word learning; Bayesian data analysis; Large
language models},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Efficiency and acceleration in the accumulation of children's
early vocabulary}
\author{Michael C. Frank}
\date{}
\begin{document}
\maketitle
\begin{abstract}
\noindent Children learn hundreds of words over the first few years of
their life. This process begins slowly but soon children are acquiring
multiple words per day. Yet there are also wide variations between
children, and the nature of this variation has not been accurately
characterized. We present a statistical model describing this process as
accelerating accumulation, with children varying in their overall
learning efficiency and their acceleration. This model provides a good
characterization of longitudinal growth across three languages and gives
insight into the sources of sociodemographic variation. Using dense
observations of children's early language environment and word
recognition speed, the model also can be used to estimate how much
variation between children is due to differences in language input and
processing. In contrast to children, large language models are not
well-described by this model: they show standard accumulator dynamics
with no acceleration and very limited variability. In sum, our model
provides a quantitative characterization of key signatures of early
vocabulary growth, providing a target for future mechanistic learning
models.
\end{abstract}


\setstretch{1.05}
Children's early vocabulary grows very rapidly during early childhood,
with large variation between children (Fenson et al. 1994, 2007; Frank
et al. 2021). The growth has theoretical, practical, and methodological
importance. From a theoretical perspective, growth mechanisms shed light
on children's fundamental learning mechanisms and how they change across
childhood (McMurray 2007; Bloom 2002; Frank et al. 2021). From a
practical perspective, early vocabulary is an important precursor -- and
predictor -- of academic achievement {[}Marchman and Fernald
(2008);CITES{]}. From a methodological perspective, vocabulary also
affords a unique psychometric opportunity to study human variation
because, unlike nearly all important human psychological metrics, there
is a true zero point -- a time before which children know no words.
Thus, absolute levels of variability can be calculated.

One dominant viewpoint is that children's vocabulary growth can be
characterized as a process of accumulation (McMurray 2007; Mitchell and
McMurray 2009; Hidaka 2013; Mollica and Piantadosi 2017; Kachergis,
Marchman, and Frank 2022). Each distinct word (type) can be
conceptualized as a ``bucket,'' and every token of language input then
is a ``drop'' that falls into its respective bucket. When each bucket is
full, the word is learned (McMurray 2007; Kachergis, Marchman, and Frank
2022). These models have been used to recover interpretable differences
in ``bucket size,'' often based on word properties including
concreteness and syntactic category (Hidaka 2013; Kachergis, Marchman,
and Frank 2022). They also provide a graded explanation for the
widely-observed ``vocabulary spurt'' phenomenon -- in which children's
rate of vocabulary learning appears to increase dramatically (Frank et
al. 2021; Ganger and Brent 2004; Gómez Díaz et al. 2024).

The accumulator view connects with a viewpoint in which the quantity of
language that children hear plays a strong causal role in the speed of
their learning (Fernald and Marchman 2012). Indeed, there is systematic
evidence that variation in children's input is related to variation in
vocabulary {[}Fernald and Marchman (2012);Weisleder and Fernald
(2013);CITES{]}. Studies of input have identified systematic variation
in \emph{quantity} in terms of sheer amount of tokens as well as
variation in \emph{quality}. Measuring what makes input high quality has
been challenging, but higher quality input likely has higher lexical
diversity, longer sentences, more declarative and interrogative content
relative to imperatives, and more elaborated discourse {[}LOTS OF
CITES{]}.

A naïve interpretation of the accumulator view would suggest that most
of the variance in vocabulary growth should be related to input. Two
recent meta-analyses complicate this view, however. Anderson et al.
(2021) showed that only a modest proportion of the variance in
vocabulary outcomes is related to input quantity (XYZ) and quality
(XYZ). A newer meta-analysis of quantity specifically confirms and
extends the proportion of variance due to quantity to 4--7\% of total
variation in vocabulary (Coffey and Snedeker 2026). Thus -- as we might
have supposed based on other research on human variation -- not all
variation in vocabulary between children can be attributed to input
differences.

As this discussion indicates, despite the promise of the accumulator
viewpoint, it has not been used successfully to understand variation
between individuals. Instead, the majority of applications have focused
on variation between words. Further, the rapidity of children's early
word learning stands as a rebuke to this view. Sometimes a small number
of examples is enough to form a lasting representation (Markson and
Bloom 1997; Woodward, Markman, and Fitzsimmons 1994). Perhaps only a
small number of high-quality instances is sufficient for learning
(Trueswell et al. 2013; Mollica and Piantadosi 2017), but if so, why do
some words take much longer to learn?

The goal of this work is to address these puzzles through systematic
investigation and extension of accumulator models. All models seek to
explain the observation that the overall size of children's vocabulary
increases supra-linearly. Does this growth imply developmental changes
in the underlying process?

Following previous work, we start with the idea that children's
\emph{internal learning ability} (not just their observed vocabulary
growth) accelerates across development (Hidaka 2013; Mayor and Plunkett
2010). In the bucket metaphor, the drops get bigger as children get
older. We begin by extending the psychometric accumulator model of
Kachergis, Marchman, and Frank (2022): our key addition is to describe
variation between individual children by modeling both their individual
learning efficiency and the acceleration of their learning. This
extension defines a longitudinal growth model that can be fit to data,
and that provides a simple reconciliation between slow accumulation and
fast mapping: the number of examples of a word necessary for learning
declines by multiple orders of magnitude from age one to age three.

To constrain our model, we use data from the MacArthur-Bates
Communicative Development Inventories {[}MB-CDI; Fenson et al.
(1994);Marchman, Dale, and Fenson (2021){]}, a popular parent report
instrument in which parents are asked to indicate which words their
child produces and understands. Here we focus exclusively on production,
which is used with older children and which tends to be a more reliable
measure (Frank et al. 2021). We make use of longitudinal data from
Wordbank (Frank et al. 2017), an open repository of data from the
MB-CDI.

To address questions about the relationship between language input and
growth, we fit a Bayesian version of our growth model. We make use of
new data resources to estimate the magnitude of linkages between input
and vocabulary growth. First, we estimate plausible population values
based on independent estimates of population variation in language input
(Coffey et al. 2024). In addition, we use measures of individual
children's language input from egocentric videos (Long et al. 2024) and
day-long home recordings (Egan-Dailey and Bergelson 2025; Adams et al.
2018; Fernald, Marchman, and Weisleder 2013) to estimate the
input-uptake relationship more precisely for a subsample of children.

Overall, our analysis supports a view in which children's vocabulary
growth is not a pure process of accumulation but rather one that
accelerates rapidly over time. We end by comparing the fit of our models
on human data to their fit on large-language models. Making use of GPT-2
models trained on human developmental data, we show that -- in contrast
to children -- these models do appear to function as pure accumulators.
This analysis exposes a critical disanalogy between LLMs and human
learners and suggests a potential route for understanding the vast
``data gap'' between children and large language models (Frank 2023;
Warstadt et al. 2023).

\section{Model}\label{model}

\begin{figure}

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{standard_model_files/figure-pdf/fig-schematic-1.pdf}

}

\caption{\label{fig-schematic}}

\end{figure}%

We present a nested set of accumulator-type models, many of which have
been presented in the literature. As we show below, each refinement of
the model contributes to its ability to describe the variability between
children. We start with the Rasch model from psychometrics (Rasch 1960;
Bond and Fox 2013), which assumes that each child \(i\) has a learning
ability \(\theta_i\) and each word \(j\) has a difficulty \(\delta_j\).
The probability that child \(i\) produces word \(j\) is

\[P(w_{i,j}=1 \mid \theta_i, \delta_j) =\frac{\exp(\theta_i - \delta_j)}{1 + \exp(\theta_i - \delta_j)}\]

Following Kachergis, Marchman, and Frank (2022), we can write our first
model as a Rasch-style accumulator model (Model 1), specifying that
\(\theta_i\) is not a single parameter but instead a function of
accumulation over time. In the simplest form:

\[\text{M1: }\theta_i(t)  = \log(r_i) + \log(t/a_0)\]

\noindent where \(r_i\) is the child's rate of language input (in tokens
per month) and \(t\) is the child's age (in months, anchored at
\(a_0\)); note that we use log age to simulate linear accumulation
because \(\exp(\theta) = r \cdot t\). This form instantiates the basic
hypothesis that the only thing that changes over time is more input, and
the only source of variation between children is variation in rate.

We compare this model to an accelerating accumulator model (Model 2), in
which the amount learned from each exposure increases with time by an
exponent \(\kappa\).

\[\text{M2: }\theta_i(t)  = \log(r_i) + \kappa ~ \log(t/a_0)\]
\noindent When \(\kappa>1\), each successive month yields more
accumulation than the last.

Neither of these models has any way to capture variation across children
beyond variation in input rate. Thus, we augment the basic accelerating
accumulator, rewriting it as the sum of either one or two individually
variable quantities:

\[\text{M3: }\theta_i(t) = \xi_i + \kappa ~ \log(t/a_0)\]

\[\text{M4: }\theta_i(t) = \xi_i + \kappa_i ~ \log(t/a_0)\]

The intercept term in both models \(\xi_i = \log(r_i) + \log(\alpha_i)\)
can then decompose individual variation into both input rate-related and
other variation in children's efficiency. Similarly, in M4, the slope
term \(\kappa_i = \kappa + \gamma \log r_i + \zeta_i\) adds
\emph{individual variation in acceleration}, decomposing acceleration
into a population term, input-related acceleration, and a child‑specific
residual acceleration \(\zeta_i\) (the part not explained by input). The
coefficient \(\gamma\) then captures the strength of the relationship
between input and acceleration.

Model 4 instantiates the idea that children vary in their base rate of
efficiency and their acceleration, creating variant of a standard
longitudinal growth model in which children vary on their slope and
intercept (Grimm, Ram, and Estabrook 2016). Note that, while we define
the relationship of \(\xi_i\) and \(\kappa_i\) to a child's input
\(r_i\), we can nevertheless fit the simplest form of the model by just
allowing these parameters to vary as random child-level slopes and
intercepts.

As we will show, this model provides a good description of variation in
children's longitudinal growth trajectories. Figure~\ref{fig-schematic}
(top) shows schematic predictions from a pure accumulator model (M1), an
accelerating accumulator (M2) in comparison to models including
child-level variation in efficiency (M3) and both efficiency and
acceleration (M4). Each model's predictions are represented as ability
scores (\(\theta\)) across age and then also projected into proportion
correct scores on a discrete set of vocabulary items, representing an
observed accuracy score that is subject to compression at floor and
ceiling.

A variety of previous work has focused on estimating the properties of
individual words (Goodman, Dale, and Li 2008; Hidaka 2013; Roy et al.
2015; Braginsky et al. 2019; Kachergis, Marchman, and Frank 2022;
Kachergis et al. 2022). These analyses reveal that there is predictable
word-level difficulty information but that only a modest portion of the
variation between words is carried by frequency information. Words can
be hard for a child to acquire because they vary also in the complexity
and concreteness of their meanings, their syntactic category and
syntactic context, their phonology, and many other factors. In the
current work, we estimate word difficulty as a free parameter, and focus
instead on variation between children.

Our analysis generally depends on the availability of longitudinal data
at the item level. The different models described above are not
distinguishable from the cross-sectional, aggregate data that are
typically considered in many analyses of early vocabulary. First,
aggregate data do not allow for the estimation of individual word
difficulties, thus the distribution of difficulties remains latent and
different difficulty distributions can be posited to explain the
accelerating shape of vocabulary growth (McMurray 2007; Mitchell and
McMurray 2009). Second, cross-sectional data do not allow for
identification of whether individual children's variation is due to
differences in efficiency (intercept) or acceleration (slope) (see
Supplemental Figure 1).

\section{Results}\label{results}

\subsection{Children's longitudinal growth reflects differences in both
efficiency and
acceleration}\label{childrens-longitudinal-growth-reflects-differences-in-both-efficiency-and-acceleration}

We first retrieved longitudinal data on monolingual,
typically-developing children's vocabulary from Wordbank (Frank et al.
2017), an open archive of data from the MacArthur-Bates Communicative
Development Inventory and its international adaptations.
Table~\ref{tbl-datasets} shows the four longitudinal datasets in
Wordbank that contained more than \(>100\) children with multiple
observations.

\begin{landscape}\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{llrrrrrclrr}

\caption{\label{tbl-datasets}Characteristics of all datasets used in the
paper. N and ages reflect the analysis samples (post-exclusion).
Cross-sectional rows pool all contributed Wordbank datasets for a
language, subsampled to at most 1,200 children. For AM2018 and FMW2013,
which enter both the input and processing analyses with slightly
different inclusion criteria, N is the union of the two subsamples.}

\tabularnewline

\toprule
\multicolumn{4}{c}{ } & \multicolumn{3}{c}{Age (months)} & \multicolumn{4}{c}{ } \\
\cmidrule(l{3pt}r{3pt}){5-7}
Citation & Language & N & Admins & Mean & Min & Max & Long. & Input & Recordings & LWL sessions\\
\midrule
\endfirsthead
\multicolumn{11}{@{}l}{\textit{(continued)}}\\
\toprule
\multicolumn{4}{c}{ } & \multicolumn{3}{c}{Age (months)} & \multicolumn{4}{c}{ } \\
\cmidrule(l{3pt}r{3pt}){5-7}
Citation & Language & N & Admins & Mean & Min & Max & Long. & Input & Recordings & LWL sessions\\
\midrule
\endhead

\endfoot
\bottomrule
\endlastfoot
\addlinespace[0.3em]
\multicolumn{11}{l}{\textbf{Wordbank longitudinal}}\\
\hspace{1em}Thal et al. (20XX) & English (American) & 653 & 1,947 & 19.1 & 12 & 29 & yes &  &  & \\
\hspace{1em}Smith et al. (20XX) & English (American) & 314 & 878 & 21.9 & 16 & 30 & yes &  &  & \\
\hspace{1em}Marchman et al. (20XX) & English (American) & 314 & 714 & 22.6 & 16 & 30 & yes &  &  & \\
\hspace{1em}Simonsen et al. (2014) & Norwegian & 1,676 & 6,347 & 25.1 & 8 & 36 & yes &  &  & \\
\hspace{1em}Hagihara et al. (2023) & Japanese & 178 & 425 & 17.4 & 8 & 34 & yes &  &  & \\
\addlinespace[0.3em]
\multicolumn{11}{l}{\textbf{Input / processing}}\\
\hspace{1em}Long et al. (2024) & English (American) & 22 & 103 & 18.6 & 9 & 32 & yes & headcam & 5,739 & \\
\hspace{1em}Egan-Dailey \& Bergelson (2025) & English (American) & 44 & 514 & 12.2 & 6 & 18 & yes & LENA & 525 & \\
\hspace{1em}Adams et al. (2018) & English (American) & 67 & 167 & 20.1 & 13 & 27 & yes & LENA & 126 & 440\\
\hspace{1em}Fernald et al. (2013) & English (American) & 60 & 142 & 23.2 & 18 & 30 & yes & LENA & 51 & 93\\
\hspace{1em}Fernald \& Marchman (2012) & English (American) & 119 & 393 & 22.9 & 14 & 30 & yes &  &  & 419\\
\addlinespace[0.3em]
\multicolumn{11}{l}{\textbf{Wordbank cross-sectional}}\\
\hspace{1em}Frank et al. (2017) & Arabic (Saudi) & 258 & 258 & 11.9 & 8 & 16 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Cantonese & 1,200 & 1,200 & 23.4 & 16 & 30 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Catalan & 1,200 & 1,200 & 19.6 & 8 & 30 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Croatian & 627 & 627 & 19.0 & 8 & 30 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Czech & 493 & 493 & 23.0 & 16 & 30 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Danish & 1,200 & 1,200 & 20.9 & 8 & 36 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Dutch & 446 & 446 & 15.6 & 8 & 31 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & English (American) & 1,200 & 1,200 & 19.3 & 8 & 30 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & English (Australian) & 1,200 & 1,200 & 20.5 & 12 & 30 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Estonian & 1,200 & 1,200 & 23.3 & 16 & 30 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Finnish & 234 & 234 & 16.5 & 9 & 24 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & French (French) & 1,200 & 1,200 & 21.6 & 8 & 30 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & German & 1,181 & 1,181 & 24.1 & 18 & 30 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Hebrew & 534 & 534 & 27.4 & 11 & 35 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Hungarian & 369 & 369 & 23.1 & 16 & 30 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Italian & 1,200 & 1,200 & 20.5 & 7 & 36 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Japanese & 846 & 846 & 20.4 & 8 & 36 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Kigiriama & 205 & 205 & 16.1 & 8 & 30 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Korean & 1,200 & 1,200 & 23.0 & 8 & 36 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Latvian & 683 & 683 & 22.3 & 8 & 36 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Mandarin (Beijing) & 1,056 & 1,056 & 23.0 & 16 & 30 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Mandarin (Taiwanese) & 1,200 & 1,200 & 21.8 & 8 & 36 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Norwegian & 1,200 & 1,200 & 23.3 & 8 & 36 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Portuguese (European) & 1,200 & 1,200 & 19.4 & 8 & 30 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Russian & 1,200 & 1,200 & 21.4 & 8 & 36 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Slovak & 1,200 & 1,200 & 20.0 & 8 & 36 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Spanish (Argentinian) & 783 & 783 & 23.3 & 16 & 33 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Spanish (European) & 1,005 & 1,005 & 18.4 & 8 & 30 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Spanish (Mexican) & 1,200 & 1,200 & 18.9 & 8 & 30 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Swedish & 1,200 & 1,200 & 18.9 & 8 & 28 &  &  &  & \\
\hspace{1em}Frank et al. (2017) & Turkish & 1,200 & 1,200 & 21.4 & 8 & 36 &  &  &  & \\*

\end{longtable}

\endgroup{}
\end{landscape}

Taking advantage of the equivalence of Rasch models to generalized
linear mixed effects models (De Boeck et al. 2011), we fit the set of
models shown in Figure~\ref{fig-schematic} as a series of logistic
regressions. As described above, this initial set of fits do not attempt
to estimate the relationship with input but instead simply attempt to
describe the distribution of vocabulary growth curves. Each model
predicted the probability of an individual child producing a particular
word as a function of age (either unmodified in M1 or multiplied by a
constant in M2) and a random effect of word difficulty. Successive
models add random intercepts (M3) and slopes (M4) by child.

Model 4, which incorporated variation in acceleration and efficiency,
was the best fitting model across all datasets, with AIC and BIC
differences shown in Table~\ref{tbl-aic}. Figure~\ref{fig-schematic}
(bottom) shows the fit of the four model variants; the increasing spread
of children's trajectories with age is especially noticeable for
low-vocabulary older children {[}who may be classified as ``late
talkers''; Fernald and Marchman (2012); Rescorla (2011){]}.\footnote{Following
  the literature, we primarily investigate linear accumulator models,
  which show power-law growth of ability over time because \(\theta\) is
  a function of \(\log(t)\). However, it is also possible that ability
  grows linearly in time, which would lead to exponential increases in
  the probability of word production. We fit linear-time models, but
  found that they were dispreferred statistically, though differences
  were relatively small within the restricted age range for which we
  have data (\(\delta\)AIC 0--4,301; see Supplemental Figure 2 for model
  fits).}

\begingroup\fontsize{8}{10}\selectfont

\begin{longtable}[t]{llrrrrr}

\caption{\label{tbl-aic}}

\tabularnewline

\toprule
\multicolumn{2}{c}{ } & \multicolumn{5}{c}{$\Delta$AIC} \\
\cmidrule(l{3pt}r{3pt}){3-7}
Model & Age & Thal & Smith & Marchman & Norwegian & Japanese\\
\midrule
M1. accumulator & — & 703,220 & 273,732 & 251,211 & 2,281,606 & 94,503\\
M2. + acceleration & linear & 206,553 & 179,872 & 134,596 & 1,377,615 & 41,169\\
M2. + acceleration & log & 204,930 & 178,471 & 133,877 & 1,348,013 & 39,054\\
M3. + efficiency var. & linear & 35,856 & 17,418 & 13,752 & 130,625 & 3,850\\
M3. + efficiency var. & log & 34,219 & 15,356 & 13,135 & 115,116 & 3,227\\
\addlinespace
M4. + acceleration var. & linear & 1,134 & 553 & 0 & 4,301 & 169\\
M4. + acceleration var. & log & 0 & 0 & 30 & 0 & 0\\
\bottomrule

\end{longtable}

\endgroup{}

\subsection{Efficiency and acceleration relate to separate demographic
predictors}\label{efficiency-and-acceleration-relate-to-separate-demographic-predictors}

\begin{figure}

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{standard_model_files/figure-pdf/fig-demographics-1.pdf}

}

\caption{\label{fig-demographics}Regression coefficients predicting
individual children's efficiency and acceleration as a function of
gender and maternal education. Black dots show meta-analytic estimates
from a random-effects meta analysis. Error bars show 95\% confidence
intervals.}

\end{figure}%

Children's vocabulary is known to be related to a number of
sociodemographic predictors, including sex and maternal education (which
is interpreted as a proxy for socioeconomic status). In particular,
female children show consistently larger vocabularies than male children
across dozens of languages and countries (Eriksson et al. 2012; Frank et
al. 2021). Similarly, children of more educated mothers tend to show
larger vocabularies, though this effect is somewhat more heterogeneous
across countries and languages (Frank et al. 2021).

Our longitudinal model offers a summary of individual children's growth
in terms of both their efficiency (intercept) and their acceleration
(slope). This decomposition allows us to ask whether these two
demographics effects -- sex and maternal education -- are seen in
efficiency, acceleration, or both. For each child in our analysis, we
extracted the best linear unbiased prediction (BLUP) from our models. We
then regressed intercept and slope terms against each demographic
predictor separately for each language. Figure~\ref{fig-demographics}
shows the coefficients from this analysis, along with a cross-language
meta-analytic estimate.

Sex effects show the predicted female advantage across all four
datasets, but this effect manifests itself only in efficiency
(\(\beta = -0.33\), \(p = < .001\)) not acceleration (\(\beta = 0\),
\(p = .939\)). In contrast, though maternal education data were only
available for two languages, effects were numerically present in both
measures, though neither was significant ( efficiency: \(\beta = 0.06\),
\(p = .157\); acceleration: \(\beta = 0.03\), \(p = .096\)). One
interpretation of these findings is that sex effects reflect a small
constant offset in average ability. In contrast, socioeconomic
differences as reflected in maternal education might continue to
compound across development (Fernald, Marchman, and Weisleder 2013; Hart
and Risley 2003).

\subsection{Population input-related variation corresponds to
meta-analytic
estimates}\label{population-input-related-variation-corresponds-to-meta-analytic-estimates}

In our prior model fits, we fit population variation in efficiency and
acceleration without considering the connection to language input. We
next consider whether this relationship can be estimated at a population
level. We use markov chain monte carlo to fit the full version of model
4, with both efficiency and acceleration linked to input variation (see
Supplemental Methods for full model specification). We estimate these
linkages by assuming a known level of population variation in language
input rate: \(\sigma_r\). We can then examine the variance due to input
variation vs.~population by fitting the parameters
\(\pi_\xi = \frac{\sigma_\alpha^2}{\sigma_\alpha^2 + \sigma_r^2}\) and
\(\pi_\kappa = \frac{\sigma_\alpha^2}{\sigma_\zeta^2 + \sigma_r^2}\),
which respectively define the proportion of population variation in
efficiency and acceleration due to input variation.

Estimating children's input range is notoriously tricky, since the rate
of language that children hear varies across cultures, families,
activities, and measurement occasions (Coffey et al. 2024). To establish
a range of plausible values for \(\sigma_r\), we surveyed the literature
for plausible estimates {[}CITES;(\textbf{sperry2018?});Coffey et al.
(2024){]}. In our main simulations we set \(\sigma_r=.53\), a value
drawn from (\textbf{sperry2018?}), who estimated a mean of 419k tokens
per month (\$\pm\$1 SD: 329k -- 957k). See Supplemental Methods for
other input estimates.

\hyperref[results]{results}

{[}Sensitivity checks{]}

{[}relation to meta-analysis{]}

\subsection{Input modestly predicts efficiency and acceleration for
individual
children}\label{input-modestly-predicts-efficiency-and-acceleration-for-individual-children}

\begin{figure}

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{standard_model_files/figure-pdf/fig-io-partition-1.pdf}

}

\caption{\label{fig-io-partition}}

\end{figure}%

While the population estimates of input-sensitivity given above match
our expectations from meta-analyses, they do not offer a direct estimate
of input couplings within individual children. For this, we turn to a
set of four longitudinal datasets that include dense home recordings
(see (\textbf{tab-datasets?})). Three of these include day-long audio
recordings using LENA (Language Environment Analysis) recorders, which
offer an automated adult word count estimate that has been validated by
a number of transcription studies (\textbf{cristia2021?}). The last
includes short video recordings of egocentric video recorded in
children's homes, with word counts estimated from automated transcripts.
Each of these provides a noisy proxy for total home input, but
nevertheless allows us to estimate models that include individual input.

We fit the same model linking input estimates to variation in efficiency
and acceleration, but this time with observations of \(r_i\) for each
child. Results for \(\pi_alpha\) and \(\pi_zeta\) are shown in
Figure~\ref{fig-io-partition}.

\hyperref[results]{RESULTS}

\subsection{Processing speed is strongly associated with
efficiency}\label{processing-speed-is-strongly-associated-with-efficiency}

Two of the datasets we included also include longitudinal reaction time
data from the looking-while-listening paradigm (LWL), archived in the
Peekbank repository (\textbf{zettersten2022?}). In LWL, children see two
pictures (e.g.~a book and a car) and their eye movements are recorded as
they hear a sentence that refers to one of the pictures (e.g., ``look at
the book''). If the child is looking at the distractor image (the car),
then their reaction time to shift their eyes to the target provides an
index of their speed of word recognition (\textbf{fernald2008?};
\textbf{frank2026?}).

We fit a modification of our model to this subset of the data (N=XYZ).
Efficiency and acceleration terms included \emph{both} input and LWL
reaction time as predictors.

\subsection{Growth in ability leads to rapid changes in learning times
for individual
words}\label{growth-in-ability-leads-to-rapid-changes-in-learning-times-for-individual-words}

\begin{figure}

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{standard_model_files/figure-pdf/fig-efficiency-1.pdf}

}

\caption{\label{fig-efficiency}}

\end{figure}%

As an illustration of the changes in efficiency and acceleration that we
observe in our data, we computed the average proportion of exposures
necessary for a child to learn a word across ages.
Figure~\ref{fig-efficiency} shows a model-derived estimate of the
average number of times a word is heard before more than 50\% of
children produce it (See SI: Changes in Word Efficiency), using
frequency estimates from the CHILDES Corpus (MacWhinney 2000; Sanchez et
al. 2019).

Across different word classes (e.g., nouns, verbs, closed class words),
efficiency increases exponentially, such that early-learned words such
as ``book'' may be heard tens of thousands of times before they are
produced, while later learned words such as ``vitamin'' might only be
heard hundreds times before being produced. Indeed, this analysis likely
understates the degree of change in efficiency as it assumes that each
exposure to a word is equally meaningful. In fact, individual exposures
vary widely in how much information they give. Sometimes words are
overheard rather than directed to the child, or lack physical context to
allow for clear inference
(\textbf{effective\_learning\_instances\_erika?};
\textbf{trueswell2014?}; Mollica and Piantadosi 2017). Thus, in line
with both intuition and experiments, the total number of exposures
required on average to learn a word might indeed be only a small handful
by age three (Markson and Bloom 1997; Bloom 2002).

\subsection{Large language models do not show acceleration in their
vocabulary
growth}\label{large-language-models-do-not-show-acceleration-in-their-vocabulary-growth}

\begin{figure}

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{standard_model_files/figure-pdf/fig-llm-acceleration-1.pdf}

}

\caption{\label{fig-llm-acceleration}Comparison of acceleration slopes
(kappa) estimated in our experiments for children in English and
Norwegian, vs.~LLM slopes per model estimated by Chang \& Bergen (2022)
and in our experiments.}

\end{figure}%

Small-scale language models trained on developmentally-realistic corpora
have become a useful tool for understanding early language development
(\textbf{huebner2022?}; \textbf{futtrell2026?}; \textbf{frank2025?}).
For our final experiments, we were interested in whether large language
models show the same patterns of developmental change in efficiency or
acceleration. We made use of work by Chang and Bergen (2022), who
extracted per-word acquisition curves from language models. They
computed logistic fits to the surprisal (negative log probability) of
individual words across training, estimating

We can compare

(\textbf{evanston2023?}) investigated

We end by providing a quantitative comparison between within-child human
learning and LLM scaling laws, showing that children's early language
learning is strikingly different from LLM scaling: it shows both steeper
scaling and greater variance in growth rate.

\section{Discussion}\label{discussion}

What we did

Longitudinal growth models efficiency and acceleration. Two different
paramters.

Where does acceleration come from? Could come from a variety of sources,
including general maturation of memory and attention, specific changes
in word recognition or processing (Fernald et al. 1998;
\textbf{frank2026?}), the increasing sophistication of inferential
strategies for word learning {[}(\textbf{smith2002?});Markman and
Wachtel (1988);etc{]}, or other sources.

Mitchell and McMurray (2009) prove that acceleration does not result
from simply leverage of vocabulary --

Role of input: Coffey 2026 variance decomposition

Furthermore, how does the accumulation process relate to the rapid
growth of vocabulary? On some models, accumulation by itself can produce
an exponential ``vocabulary explosion'' while the child's own learning
abilities remain constant. On other accounts, however, the child's own
abilities change over development. These changes could be due to the
accumulation of language allowing bootstrapping (e.g., via mutual
excusivity or the shape bias), they could be through faster processing
(Fernald rich get richer), or they could be via general maturation
(e.g., better memory, faster processing). Or all of these.

Thus, modeling human learning requires positing other sources of
variability and acceleration. Sources of variability could include from
variation in interactional input quality, genetic variation between
children, environmental richness not captured by input, etc. Sources of
acceleration could include increases in processing efficiency,
learning-to-learn including mutual exclusivity, shape bias, syntactic
bootstrapping, as well as domain general changes in perception,
processing speed, memory, attention or other aspects of cognition. The
key to understanding children's data efficiency may thus lie in better
understanding when and how children's learning accelerates with
maturation and experience.

Continuous variation or clusters? (Pinstock and Schramm 2026; Singletary
et al. 2025) We think it's just continuous variation (Supplement)

Network models and their predictions e.g. (\textbf{steyvers2005?};
\textbf{hills2009?}; Fourtassi, Bian, and Frank 2020)

\section{Methods}\label{methods}

\subsection{Data and Code}\label{data-and-code}

Data were retrieved from Wordbank using the \texttt{wordbankr} package
(Frank et al. 2017), childes-db using childesr (Sanchez et al. 2019),
and peekbank using peekbankr (\textbf{zettersten2022?}). BabyView data
are from release 2025.2, specifically those used by (\textbf{tan2026?}).
SEEDLings data are downloaded from the materials provided by Egan-Dailey
and Bergelson (2025).

Reproducible code for this paper is available at
http://github.com/langcog/standard-model-2.

\subsection{Models}\label{models}

\subsubsection{Frequentist models}\label{frequentist-models}

Initial models were fit with \texttt{glmer} (\textbf{glmer?}), with the
following specifications:

\begin{itemize}
\tightlist
\item
  M1:
  \texttt{produces\ \textasciitilde{}\ offset(log\_age)\ +\ (1\ \textbar{}\ item)}
\item
  M2:
  \texttt{produces\ \textasciitilde{}\ 1\ +\ log\_age\ +\ (1\ \textbar{}\ item)}
\item
  M3:
  \texttt{produces\ \textasciitilde{}\ 1\ +\ log\_age\ +\ (1\ \textbar{}\ item)\ +\ (1\ \textbar{}\ child)}
\item
  M4:
  \texttt{produces\ \textasciitilde{}\ 1\ +\ log\_age\ +\ (1\ \textbar{}\ item)\ +\ (log\_age\ \textbar{}\ child)}
\end{itemize}

Linear variants reported in the supplement used linear age rather than
log age.

\subsubsection{Bayesian models}\label{bayesian-models}

Bayesian models were fit using Stan (\textbf{stan?}).

Priors

Inference

\subsubsection{Input}\label{input}

\subsubsection{GPT-2 models}\label{gpt-2-models}

We trained XYZ

\section{References}\label{references}

Claude Code was used for literature review, code generation,
visualization, and simulation infrastructure. All writing is original to
the author.

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-adams2018}
Adams, Katherine A., Virginia A. Marchman, Elizabeth C. Loi, Melanie D.
Ashland, Anne Fernald, and Heidi M. Feldman. 2018. {``Caregiver Talk and
Medical Risk as Predictors of Language Outcomes in Full Term and Preterm
Toddlers.''} \emph{Child Development} 89 (5): 1674--90.

\bibitem[\citeproctext]{ref-anderson2021}
Anderson, Nina J., Susan A. Graham, Heather Prime, Jennifer M. Jenkins,
and Sheri Madigan. 2021. {``Linking Quality and Quantity of Parental
Linguistic Input to Child Language Skills: A Meta-Analysis.''}
\emph{Child Development} 92 (2): 484--501.

\bibitem[\citeproctext]{ref-bloom2002}
Bloom, Paul. 2002. \emph{How Children Learn the Meanings of Words}. MIT
press.

\bibitem[\citeproctext]{ref-bond2013}
Bond, Trevor G, and Christine M Fox. 2013. \emph{Applying the Rasch
Model: Fundamental Measurement in the Human Sciences}. Psychology Press.

\bibitem[\citeproctext]{ref-braginsky2019}
Braginsky, Mika, Daniel Yurovsky, Virginia A Marchman, and Michael C
Frank. 2019. {``Consistency and Variability in Children's Word Learning
Across Languages.''} \emph{Open Mind} 3: 52--67.

\bibitem[\citeproctext]{ref-chang2022}
Chang, Tyler A., and Benjamin K. Bergen. 2022. {``Word Acquisition in
Neural Language Models.''} \emph{Transactions of the Association for
Computational Linguistics} 10: 1--16.
\url{https://doi.org/10.1162/tacl_a_00444}.

\bibitem[\citeproctext]{ref-coffey2024}
Coffey, Joseph R., Okko Räsänen, Camila Scaff, and Alejandrina Cristia.
2024. {``The Difficulty and Importance of Estimating the Lower and Upper
Bounds of Infant Speech Exposure.''} In \emph{Proceedings of Interspeech
2024}, 3615. Kos, Greece.
\url{https://doi.org/10.21437/Interspeech.2024-2102}.

\bibitem[\citeproctext]{ref-coffey2026}
Coffey, Joseph R., and Jesse Snedeker. 2026. {``How Strong Is the
Relationship Between Caregiver Speech and Language Development? {A}
Meta-Analysis.''} \emph{Journal of Child Language} 53: 435--70.
\url{https://doi.org/10.1017/S0305000924000692}.

\bibitem[\citeproctext]{ref-deboeck2011}
De Boeck, Paul, Marjan Bakker, Robert Zwitser, Michel Nivard, Abe
Hofman, Francis Tuerlinckx, and Ivailo Partchev. 2011. {``The Estimation
of Item Response Models with the Lmer Function from the Lme4 Package in
r.''} \emph{Journal of Statistical Software} 39: 1--28.

\bibitem[\citeproctext]{ref-egan2025}
Egan-Dailey, Shannon, and Elika Bergelson. 2025. {``Early Child Measures
Outpredict Input Measures of Preschool Language Skills in US English
Learners.''} \emph{Developmental Psychology}.

\bibitem[\citeproctext]{ref-eriksson2012}
Eriksson, Mårten, Peter B Marschik, Tiia Tulviste, Margareta Almgren,
Miguel Pérez Pereira, Sonja Wehberg, Ljubica Marjanovič-Umek, Frederique
Gayraud, Melita Kovacevic, and Carlos Gallego. 2012. {``Differences
Between Girls and Boys in Emerging Language Skills: Evidence from 10
Language Communities.''} \emph{British Journal of Developmental
Psychology} 30 (2): 326--43.

\bibitem[\citeproctext]{ref-fenson2007}
Fenson, Larry et al. 2007. \emph{MacArthur-Bates Communicative
Development Inventories}. Baltimore, MD: Paul H. Brookes Publishing
Company.

\bibitem[\citeproctext]{ref-fenson1994}
Fenson, Larry, Philip S Dale, J Steven Reznick, Elizabeth Bates, Donna J
Thal, Stephen J Pethick, Michael Tomasello, Carolyn B Mervis, and Joan
Stiles. 1994. {``Variability in Early Communicative Development.''}
\emph{Monographs of the Society for Research in Child Development},
i--185.

\bibitem[\citeproctext]{ref-fernald2012}
Fernald, Anne, and Virginia A Marchman. 2012. {``Individual Differences
in Lexical Processing at 18 Months Predict Vocabulary Growth in
Typically Developing and Late-Talking Toddlers.''} \emph{Child
Development} 83 (1): 203--22.

\bibitem[\citeproctext]{ref-fernald2013}
Fernald, Anne, Virginia A Marchman, and Adriana Weisleder. 2013. {``SES
Differences in Language Processing Skill and Vocabulary Are Evident at
18 Months.''} \emph{Developmental Science} 16 (2): 234--48.

\bibitem[\citeproctext]{ref-fernald1998}
Fernald, Anne, John P. Pinto, Daniel Swingley, Amy Weinberg, and Gerald
W. McRoberts. 1998. {``Rapid Gains in Speed of Verbal Processing by
Infants in the 2nd Year.''} \emph{Psychological Science} 9 (3): 228--31.

\bibitem[\citeproctext]{ref-fourtassi2020}
Fourtassi, Abdellah, Yuan Bian, and Michael C Frank. 2020. {``The Growth
of Children's Semantic and Phonological Networks: Insight from 10
Languages.''} \emph{Cognitive Science} 44 (7): e12847.
\url{https://doi.org/10.1111/cogs.12847}.

\bibitem[\citeproctext]{ref-frank2023}
Frank, Michael C. 2023. {``Bridging the Data Gap Between Children and
Large Language Models.''} \emph{Trends in Cognitive Sciences} 27 (11):
990--92.

\bibitem[\citeproctext]{ref-frank2021}
Frank, Michael C, Mika Braginsky, Daniel Yurovsky, and Virginia A
Marchman. 2021. \emph{Variability and Consistency in Early Language
Learning: The Wordbank Project}. MIT Press.

\bibitem[\citeproctext]{ref-frank2017}
Frank, Michael C, Mika Braginsky, Daniel Yurovsky, and Virginia A.
Marchman. 2017. {``Wordbank: An Open Repository for Developmental
Vocabulary Data.''} \emph{Journal of Child Language} 44 (3): 677--94.

\bibitem[\citeproctext]{ref-ganger2004}
Ganger, Jennifer, and Michael R. Brent. 2004. {``Reexamining the
Vocabulary Spurt.''} \emph{Developmental Psychology} 40 (4): 621--32.
\url{https://doi.org/10.1037/0012-1649.40.4.621}.

\bibitem[\citeproctext]{ref-gomezdiaz2024}
Gómez Díaz, Miranda, Laia Fibla, Rachel Ka-Ying Tsui, and Krista
Byers-Heinlein. 2024. {``Testing Theories of the Vocabulary Spurt with
Monolingual and Bilingual Infants.''} \emph{Developmental Psychology} 60
(8): 1357--71. \url{https://doi.org/10.1037/dev0001777}.

\bibitem[\citeproctext]{ref-goodman2008}
Goodman, Judith C, Philip S Dale, and Ping Li. 2008. {``Does Frequency
Count? Parental Input and the Acquisition of Vocabulary.''}
\emph{Journal of Child Language} 35 (3): 515--31.

\bibitem[\citeproctext]{ref-grimm2016}
Grimm, Kevin J, Nilam Ram, and Ryne Estabrook. 2016. \emph{Growth
Modeling: Structural Equation and Multilevel Modeling Approaches}.
Guilford Publications.

\bibitem[\citeproctext]{ref-hagihara2023}
Hagihara, Hiromichi, Monica Barbir, Mikako Ishibashi, Yasuhiro Kanakogi,
Masaharu Kato, Irena Lovcevic, Youtao Lu, et al. 2023. {``A Sharable
Merged Dataset on {Japanese} Children's Vocabulary Measures Using the
{Japanese} {MacArthur}--{Bates} {Communicative} {Development}
{Inventory}.''} OSF. \url{https://doi.org/10.17605/osf.io/s5ydw}.

\bibitem[\citeproctext]{ref-hart2003}
Hart, Betty, and Todd R Risley. 2003. {``The Early Catastrophe: The 30
Million Word Gap by Age 3.''} \emph{American Educator} 27 (1): 4--9.

\bibitem[\citeproctext]{ref-hidaka2013}
Hidaka, Shohei. 2013. {``A Computational Model Associating Learning
Process, Word Attributes, and Age of Acquisition.''} \emph{PloS One} 8
(11).

\bibitem[\citeproctext]{ref-kachergis2022b}
Kachergis, George, Virginia A Marchman, Philip S Dale, Jessica
Mankewitz, and Michael C Frank. 2022. {``Online Computerized Adaptive
Tests of Children's Vocabulary Development in English and Mexican
Spanish.''} \emph{Journal of Speech, Language, and Hearing Research} 65
(6): 2288--308.

\bibitem[\citeproctext]{ref-kachergis2022}
Kachergis, George, Virginia A Marchman, and Michael C Frank. 2022.
{``Toward a {`Standard Model'} of Early Language Learning.''}
\emph{Current Directions in Psychological Science} 31 (1): 20--27.

\bibitem[\citeproctext]{ref-long2024}
Long, Bria, Robert Z Sparks, Violet Xiang, Stefan Stojanov, Zi Yin,
Grace E Keene, Alvin WM Tan, et al. 2024. {``The BabyView Dataset:
High-Resolution Egocentric Videos of Infants' and Young Children's
Everyday Experiences.''} \emph{arXiv Preprint arXiv:2406.10447}.

\bibitem[\citeproctext]{ref-macwhinney2000}
MacWhinney, Brian. 2000. \emph{The {CHILDES} Project: Tools for
Analyzing Talk}. Vol. 1. Psychology Press.

\bibitem[\citeproctext]{ref-marchman2021}
Marchman, Virginia A, Philip Dale, and Larry Fenson. 2021.
\emph{MacArthur-Bates Communicative Development Inventories User's Guide
and Technical Manual, Third Edition}. Brookes Publishing.

\bibitem[\citeproctext]{ref-marchman2008}
Marchman, Virginia A, and Anne Fernald. 2008. {``Speed of Word
Recognition and Vocabulary Knowledge in Infancy Predict Cognitive and
Language Outcomes in Later Childhood.''} \emph{Developmental Science} 11
(3): F9--16.

\bibitem[\citeproctext]{ref-markman1988}
Markman, Ellen M., and Gwyn F. Wachtel. 1988. {``Children's Use of
Mutual Exclusivity to Constrain the Meanings of Words.''}
\emph{Cognitive Psychology} 20 (2): 121--57.

\bibitem[\citeproctext]{ref-markson1997}
Markson, Lori, and Paul Bloom. 1997. {``Evidence Against a Dedicated
System for Word Learning in Children.''} \emph{Nature} 385 (6619):
813--15.

\bibitem[\citeproctext]{ref-mayor2010}
Mayor, Julien, and Kim Plunkett. 2010. {``Vocabulary Spurt: Are Infants
Full of {Zipf}?''} In \emph{Proceedings of the 32nd Annual Conference of
the Cognitive Science Society}. Vol. 32.

\bibitem[\citeproctext]{ref-mcmurray2007}
McMurray, Bob. 2007. {``Defusing the Childhood Vocabulary Explosion.''}
\emph{Science} 317 (5838): 631--31.

\bibitem[\citeproctext]{ref-mitchell2009}
Mitchell, C., and B. McMurray. 2009. {``On Leveraged Learning in Lexical
Acquisition and Its Relationship to Acceleration.''} \emph{Cognitive
Science} 33 (8): 1503--23.

\bibitem[\citeproctext]{ref-mollica2017}
Mollica, Francis, and Steven T Piantadosi. 2017. {``How Data Drive Early
Word Learning: A Cross-Linguistic Waiting Time Analysis.''} \emph{Open
Mind} 1 (2): 67--77.

\bibitem[\citeproctext]{ref-pinstock2026}
Pinstock, Eveline, and Satyam Antonio Schramm. 2026. {``Vocabulary
Trajectories in {German}-Speaking Children from 18 Months to Three
Years: A Growth Mixture Model.''} \emph{Journal of Child Language} 53
(1): 62--79. \url{https://doi.org/10.1017/S0305000924000503}.

\bibitem[\citeproctext]{ref-rasch1960}
Rasch, Georg. 1960. \emph{Probabilistic Models for Some Intelligence and
Attainment Tests}. Copenhagen, Denmark: Danish Institute for Educational
Research.

\bibitem[\citeproctext]{ref-rescorla2011}
Rescorla, Leslie. 2011. {``Late Talkers: Do Good Predictors of Outcome
Exist?''} \emph{Developmental Disabilities Research Reviews} 17 (2):
141--50.

\bibitem[\citeproctext]{ref-roy2015}
Roy, Brandon C., Michael C Frank, Philip DeCamp, Matthew Miller, and Deb
Roy. 2015. {``Predicting the Birth of a Spoken Word.''}
\emph{Proceedings of the National Academy of Sciences} 112 (41):
12663--68.

\bibitem[\citeproctext]{ref-sanchez2019}
Sanchez, Alessandro, Stephan C. Meylan, Mika Braginsky, Kyle E.
MacDonald, Daniel Yurovsky, and Michael C Frank. 2019. {``Childes-Db: A
Flexible and Reproducible Interface to the Child Language Data Exchange
System.''} \emph{Behavior Research Methods} 51 (4): 1928--41.

\bibitem[\citeproctext]{ref-simonsen2014}
Simonsen, Hanne Gram, Kristian Emil Kristoffersen, Dorthe Bleses, Sonja
Wehberg, and Rune Nørgård Jørgensen. 2014. {``The {Norwegian}
{Communicative} {Development} {Inventories}: Reliability, Main
Developmental Trends and Gender Differences.''} \emph{First Language} 34
(1): 3--23. \url{https://doi.org/10.1177/0142723713510997}.

\bibitem[\citeproctext]{ref-singletary2025}
Singletary, Britt, Hui Jiang, Winifred Graham Wilberforce, Daniela
Avelar, Kristina Strother-Garcia, and Laura M. Justice. 2025.
{``Examining Early Vocabulary Growth Trajectories in Late Talkers in a
Low-Income Longitudinal Sample.''} \emph{Infancy} 30 (4): e70036.
\url{https://doi.org/10.1111/infa.70036}.

\bibitem[\citeproctext]{ref-thal2013}
Thal, Donna J., Virginia A. Marchman, and J. Bruce Tomblin. 2013.
{``Late Talking Toddlers: Characterization and Prediction of Continued
Delay.''} In \emph{Late Talkers: Language Development, Interventions,
and Outcomes}, edited by L. Rescorla and P. Dale. Baltimore, MD: Brookes
Publishing.

\bibitem[\citeproctext]{ref-trueswell2013}
Trueswell, John C, Tamara Nicol Medina, Alon Hafri, and Lila R Gleitman.
2013. {``Propose but Verify: Fast Mapping Meets Cross-Situational Word
Learning.''} \emph{Cognitive Psychology} 66 (1): 126--56.

\bibitem[\citeproctext]{ref-warstadt2023}
Warstadt, Alex, Aaron Mueller, Leshem Choshen, Ethan Wilcox, Chengxu
Zhuang, Juan Ciro, Rafael Mosquera, et al. 2023. {``Findings of the
BabyLM Challenge: Sample-Efficient Pretraining on Developmentally
Plausible Corpora.''} In \emph{Proceedings of the Babylm Challenge at
the 27th Conference on Computational Natural Language Learning}, 1--34.

\bibitem[\citeproctext]{ref-weisleder2013}
Weisleder, A., and A. Fernald. 2013. {``Talking to Children Matters:
Early Language Experience Strengthens Processing and Builds
Vocabulary.''} \emph{Psychological Science} 24 (11): 2143--52.
\url{https://doi.org/10.1177/0956797613488145}.

\bibitem[\citeproctext]{ref-woodward1994}
Woodward, Amanda L, Ellen M Markman, and Colleen M Fitzsimmons. 1994.
{``Rapid Word Learning in 13-and 18-Month-Olds.''} \emph{Developmental
Psychology} 30 (4): 553.

\end{CSLReferences}




\end{document}
